### ISSUE TITLE
Add Travis CI build for LedTest sketch

### ISSUE THREAD

**Issue by aentinger** [107-systems/VidorCameraAdapter#9]
@generationmake created `LedTest.ino` which allows to check if all LEDs on the camera adapter board are happily blinking (so one can easily identify soldering errors). Adding this sketch to a CI build allows us to keep track of its continued working over time.

@per1234 may I ask you to do this?

**Comment by per1234** [comment]
Do you want me to add the spell check and formatting check as done in the CI builds for the other repos, or only a compilation test of the sketch?

**Comment by aentinger** [comment]
If it doesn't trouble you too much please add formatting and spell checking too. Helps us keep consistency.
